### PR TITLE
added pydpf post cheatsheet

### PR DESCRIPTION
**Pull request by vnamdeo**
@abhishekchitwar and @Revathyvenugopal162 : Added PyDPF Post Cheatsheet for the review. Please find attached PDF file of cheatsheet.
[pydpf-post_cheat_sheet.pdf](https://github.com/ansys/pyansys-cheat-sheet/files/12333708/pydpf-post_cheat_sheet.pdf)

### CODE REVIEW

**Review by vnamdeo — COMMENTED** [review]
Looks good

**Comment by vnamdeo** [comment]
@Revathyvenugopal162 @EstherProsperi @abhishekchitwar Please review it so we can merge it to main branch. Thanks !

**Comment by EstherProsperi** [comment]
[pydpf-post_cheat_sheet.pdf](https://github.com/ansys/pyansys-cheat-sheet/files/12334981/pydpf-post_cheat_sheet.pdf)

**Comment by vnamdeo** [comment]
@Revathyvenugopal162 @EstherProsperi Please find attached revised cheatsheet and let me know your suggestions if any.

[pydpf-post_cheat_sheet_rev.pdf](https://github.com/ansys/pyansys-cheat-sheet/files/12359056/pydpf-post_cheat_sheet_rev.pdf)

**Review by Revathyvenugopal162 — APPROVED** [review]

**Comment by Revathyvenugopal162** [comment]
LGTM , Thanks for the cheatsheet @vnamdeo and for the review  @EstherProsperi

**Pull request merged**
