### PR TITLE
Fix Style in pyMAPDL cheat sheet

### PR DESCRIPTION
**Pull request by da1910**
Couple of english suggestions, a typo, lots of PEP-8 and a change in the GET command cell

### CODE REVIEW

**Comment by da1910** [comment]
Looks like the CI isn't working correctly right now

**Comment by da1910** [comment]
I see the following:

image

Which is definitely a good start...

**Comment by RobPasMue** [comment]
Sorry, don't know why it closed the PR automatically

**Comment by da1910** [comment]
This is closer to PEP-8 compliance. I'm not really sure what the intended audience is for these, on the one hand it looks aimed at beginners, but then has advanced plotting content. It's also not really a cheatsheet...

**Review by Revathyvenugopal162 — APPROVED** [review]

**Comment by Revathyvenugopal162** [comment]
> This is closer to PEP-8 compliance. I'm not really sure what the intended audience is for these, on the one hand it looks aimed at beginners, but then has advanced plotting content. It's also not really a cheatsheet...

The goal of this cheatsheets is to act as handy pages for new users to get going with PyAnsys, as request from ACE. it is the supplement the AIC course , bit more learning inclined.

**Comment by RobPasMue** [comment]
Can we merge this

**Comment by Revathyvenugopal162** [comment]
merging this. Thanks for the PR @da1910 and the review and feedbacks @RobPasMue

**Pull request merged**
